<?xml version="1.0" encoding="utf-8"?><Database Name="HKSPA_dev" Class="CategoryDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=HKSPA_dev;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MySqlConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.view_Category" Member="view_Categories">
    <Type Name="view_Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.view_Promo" Member="view_Promos">
    <Type Name="view_Promo">
      <Column Name="PromoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PromoSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromoSingleImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PromoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UnitFunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsSingleDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="PromoName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PromoDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PromoImageUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_ProductImage" Member="view_ProductImages">
    <Type Name="view_ProductImage">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailWidth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailHeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NavigateUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CameraModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryName" Member="CategoryNames">
    <Type Name="CategoryName">
      <Column Name="CategoryNameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AlbumName" Member="AlbumNames">
    <Type Name="AlbumName">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlbumID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AlbumName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>